services:
  db:
    image: postgres:17
    container_name: fms_postgres
    environment:
      POSTGRES_USER: fms_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: fms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth_service:
    build:
      context: ./auth_service
    container_name: auth_service
    ports:
      - "8002:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://fms_user:12345@db:5432/fms_db
      - JWT_SECRET_KEY=your-secret-key-here
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  payables-service:
    build:
      context: ./payables-service
    container_name: payables_service
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ledger_db
      - ledger-service
      - auth_service
    environment:
      - DATABASE_URL=postgresql://fms_user:12345@db:5432/fms_db
      - JWT_SECRET_KEY=your-secret-key-here
      - JWT_ALGORITHM=HS256
      - SERVICE_SECRET=your-service-secret-here
      - AUTH_SERVICE_URL=http://auth_service:8000

  ledger_db:
    image: postgres:17
    container_name: ledger_db
    restart: always
    environment:
      POSTGRES_USER: ledger_user
      POSTGRES_PASSWORD: ledger_pass
      POSTGRES_DB: ledger_db
    ports:
      - "5433:5432"
    volumes:
      - ledger_pgdata:/var/lib/postgresql/data

  ledger-service:
    build:
      context: ./ledger-service
    container_name: ledger-service
    depends_on:
      - ledger_db
    environment:
      - DATABASE_URL=postgresql://ledger_user:ledger_pass@ledger_db:5432/ledger_db
      - SERVICE_SECRET=your-service-secret-here
      - JWT_ALGORITHM=HS256
    ports:
      - "8001:8000"

volumes:
  postgres_data:
  ledger_pgdata:
