version: "3.9"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: fms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth_service:
    build: ./auth_service
    environment:
      DATABASE_URL: postgresql://postgres:root123@db:5432/fms_db
      AUTH_SECRET_KEY: CHANGE_THIS_SECRET
    ports:
      - "8001:8001"
    depends_on:
      - db

volumes:
  pgdata: