version: "3.9"

services:
  db:
    image: postgres:16
    container_name: fms_postgres
    environment:
      POSTGRES_USER: fms_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: fms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth_service:
    build:
      context: ./auth_service
    container_name: auth_service
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://fms_user:12345@db:5432/fms_db
      - JWT_SECRET_KEY=your-auth-secret-key
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - SERVICE_SECRET=shared-service-secret
    ports:
      - "8001:8000"

  payables_service:
    build:
      context: ./payables-service  # Changed from payables_service to payables-service
    container_name: payables_service
    depends_on:
      - db
      - auth_service
      - ledger_service  # Added dependency on ledger_service
    environment:
      - DATABASE_URL=postgresql://fms_user:12345@db:5432/fms_db
      - JWT_SECRET_KEY=your-auth-secret-key   # <--- match with auth_service
      - SERVICE_SECRET=shared-service-secret
      - AUTH_SERVICE_URL=http://auth_service:8000
      - LEDGER_SERVICE_URL=http://ledger_service:8000  # Added ledger service URL
    ports:
      - "8002:8000"

  ledger_service:
    build:
      context: ./ledger-service  # Changed from ledger_service to ledger-service
    container_name: ledger_service
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://fms_user:12345@db:5432/fms_db
      - JWT_SECRET_KEY=your-auth-secret-key   # <--- match with auth_service
      - SERVICE_SECRET=shared-service-secret
      - JWT_ALGORITHM=HS256
    ports:
      - "8003:8000"

  api_gateway:
    build:
      context: ./api_gateway
    container_name: api_gateway
    depends_on:
      - auth_service
      - payables_service
      - ledger_service
    environment:
      - AUTH_SERVICE_URL=http://auth_service:8000
      - PAYABLES_SERVICE_URL=http://payables_service:8000
      - LEDGER_SERVICE_URL=http://ledger_service:8000
      - JWT_SECRET_KEY=your-auth-secret-key   # <--- match with auth_service
    ports:
      - "8000:8000"

volumes:
  postgres_data:
